In [40]:
import warnings 
import zipfile
import numpy as np
import pandas as pd

class recovery_file:
    def __init__(self, neuron_type= 'L5PC', num_ap = 1, V_data = None, I_data = None, t_data = None ):
        self.neuron = neuron_type
        self.num_ap = num_ap
        self.V_data  = V_data
        self.I_data = I_data
        self.t_data = t_data
    def load(self):
        if self.neuron == 'L5PC':
            if self.num_ap >= 2:
                warnings.warn("For multiple action potentials, defaulted to general repetitive firing")
                fname = 'gt_multa'
            elif self.num_ap == 0:
                fname = 'gt_noa'
            else:
                print('Default choosen of 1 Action Potential')
                fname = 'gt_1a'
            with zipfile.ZipFile('./sim_data/' + fname + '.zip', 'r') as zip_ref:
                zip_ref.extractall()
            with open(fname + '.csv') as csvfile:
                df = pd.read_csv(csvfile)
            self.I_data = df['stim'].to_numpy()
            self.V_data = df['voltage'].to_numpy()
            self.t_data = df['time'].to_numpy() 
            self.dt = df['time'][1]-df['time'][0]
            self.V0 = df['voltage'][0]
        elif self.neuron == 'HH':
            if self.num_ap >= 2: 
                warnings.warn("For multiple action potentials, defaulted to general repetitive firing")
                fname = 'hh_multap'
            elif self.num_ap == 0:
                fname = 'hh_noap'
            else: 
                fname = 'hh_1ap'
            with zipfile.ZipFile('./sim_data/' + fname + '.zip', 'r') as zip_ref:
                csv_file_name = zip_ref.namelist()[0]
                with zip_ref.open(csv_file_name) as csv_file:
                    df = pd.read_csv(csv_file)
            self.V_data = df['voltage'].to_numpy()
            self.I_data = df['stim'].to_numpy()
            self.t_data = df['time'].to_numpy() 
            self.dt = df['time'][1]-df['time'][0]
            self.V0 = df['voltage'][0]
        elif self.neuron == 'manual':
            if self.V_data is None or self.I_data is None or self.t_data is None:
                raise Exception("Missing parameter, argument requires voltage, time, and input stim array ")
                pass
            else:
                self.V_data  = self.V_data.to_numpy()
                self.I_data = self.I_data.to_numpy()
                self.t_data = self.t_data.to_numpy()
                self.V0 = self.V_data[0]
                self.dt = self.t_data[1]-self.t_data[0]
        else:
            raise Exception("Sorry this is not a valid choice of neuron model for this problem, please choose HH, L5PC, or manually insert your data ")
            pass #raise warning here to input valid input

In [41]:
test_L5 = recovery_file('L5PC', 3)
test_L5.load()
print(test_L5.V_data)
print(test_L5.I_data)
print(test_L5.t_data)
print(test_L5.dt)
print(test_L5.V0)

[-80.       -80.000114 -80.00022  ... -81.551445 -81.55139  -81.55134 ]
[0. 0. 0. ... 0. 0. 0.]
[0.00000e+00 1.00000e-03 2.00000e-03 ... 2.49998e+02 2.49999e+02
 2.50000e+02]
0.001
-80.0


/var/folders/y5/qy3mtncn089941sxdcnsvzn80000gn/T/ipykernel_13395/2417480605.py:16: UserWarning: For multiple action potentials, defaulted to general repetitive firing
  warnings.warn("For multiple action potentials, defaulted to general repetitive firing")


In [42]:
test_HH = recovery_file('HH', 0)
test_HH.load()
print(test_HH.V_data)
print(test_HH.I_data)
print(test_HH.t_data)
print(test_HH.dt)
print(test_HH.V0)

[-65.         -64.98267944 -64.96518996 ... -64.19355688 -64.19355688
 -64.19355688]
[1. 1. 1. ... 1. 1. 1.]
[0.00000e+00 2.50000e-02 5.00000e-02 ... 2.49925e+02 2.49950e+02
 2.49975e+02]
0.025
-65.0


In [43]:
zip_file_path = './sim_data/gt_1a_100.zip'
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    # Assume there is only one CSV file in the zip (you might need to modify this if there are multiple CSV files)
    csv_file_name = zip_ref.namelist()[0]

    # Read the CSV file directly from the zip file into a pandas DataFrame
    with zip_ref.open(csv_file_name) as csv_file:
        df_test = pd.read_csv(csv_file)
        

In [44]:
test_man = recovery_file('manual',1 , df_test['voltage'], df_test['stim'], df_test['time'] )
test_man.load()
print(test_man.V_data)
print(test_man.I_data)
print(test_man.t_data)
print(test_man.dt)
print(test_man.V0)

[-80.       -80.001144 -80.00217  ... -73.5554   -73.55887  -73.56233 ]
[0. 0. 0. ... 0. 0. 0.]
[0.00000e+00 1.25000e-02 2.50000e-02 ... 9.99750e+01 9.99875e+01
 1.00000e+02]
0.0125
-80.0
